/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard/history'
import { Route as DashboardExamRouteImport } from './routes/dashboard/exam'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardQuizIndexRouteImport } from './routes/dashboard/quiz/index'
import { Route as DashboardExperimentIdIndexRouteImport } from './routes/dashboard/$experimentId/index'
import { Route as DashboardResultsAttemptIdRouteImport } from './routes/dashboard/results/$attemptId'
import { Route as DashboardQuizTopicRouteImport } from './routes/dashboard/quiz/$topic'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExamRoute = DashboardExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQuizIndexRoute = DashboardQuizIndexRouteImport.update({
  id: '/quiz/',
  path: '/quiz/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExperimentIdIndexRoute =
  DashboardExperimentIdIndexRouteImport.update({
    id: '/$experimentId/',
    path: '/$experimentId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardResultsAttemptIdRoute =
  DashboardResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardQuizTopicRoute = DashboardQuizTopicRouteImport.update({
  id: '/quiz/$topic',
  path: '/quiz/$topic',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/exam': typeof DashboardExamRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/quiz/$topic': typeof DashboardQuizTopicRoute
  '/dashboard/results/$attemptId': typeof DashboardResultsAttemptIdRoute
  '/dashboard/$experimentId/': typeof DashboardExperimentIdIndexRoute
  '/dashboard/quiz/': typeof DashboardQuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/exam': typeof DashboardExamRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/quiz/$topic': typeof DashboardQuizTopicRoute
  '/dashboard/results/$attemptId': typeof DashboardResultsAttemptIdRoute
  '/dashboard/$experimentId': typeof DashboardExperimentIdIndexRoute
  '/dashboard/quiz': typeof DashboardQuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/dashboard/exam': typeof DashboardExamRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/quiz/$topic': typeof DashboardQuizTopicRoute
  '/dashboard/results/$attemptId': typeof DashboardResultsAttemptIdRoute
  '/dashboard/$experimentId/': typeof DashboardExperimentIdIndexRoute
  '/dashboard/quiz/': typeof DashboardQuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/exam'
    | '/dashboard/history'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/quiz/$topic'
    | '/dashboard/results/$attemptId'
    | '/dashboard/$experimentId/'
    | '/dashboard/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/exam'
    | '/dashboard/history'
    | '/auth'
    | '/dashboard'
    | '/dashboard/quiz/$topic'
    | '/dashboard/results/$attemptId'
    | '/dashboard/$experimentId'
    | '/dashboard/quiz'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/exam'
    | '/dashboard/history'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/quiz/$topic'
    | '/dashboard/results/$attemptId'
    | '/dashboard/$experimentId/'
    | '/dashboard/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/exam': {
      id: '/dashboard/exam'
      path: '/exam'
      fullPath: '/dashboard/exam'
      preLoaderRoute: typeof DashboardExamRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/quiz/': {
      id: '/dashboard/quiz/'
      path: '/quiz'
      fullPath: '/dashboard/quiz/'
      preLoaderRoute: typeof DashboardQuizIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/$experimentId/': {
      id: '/dashboard/$experimentId/'
      path: '/$experimentId'
      fullPath: '/dashboard/$experimentId/'
      preLoaderRoute: typeof DashboardExperimentIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/results/$attemptId': {
      id: '/dashboard/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/dashboard/results/$attemptId'
      preLoaderRoute: typeof DashboardResultsAttemptIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/quiz/$topic': {
      id: '/dashboard/quiz/$topic'
      path: '/quiz/$topic'
      fullPath: '/dashboard/quiz/$topic'
      preLoaderRoute: typeof DashboardQuizTopicRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardExamRoute: typeof DashboardExamRoute
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardQuizTopicRoute: typeof DashboardQuizTopicRoute
  DashboardResultsAttemptIdRoute: typeof DashboardResultsAttemptIdRoute
  DashboardExperimentIdIndexRoute: typeof DashboardExperimentIdIndexRoute
  DashboardQuizIndexRoute: typeof DashboardQuizIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardExamRoute: DashboardExamRoute,
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardQuizTopicRoute: DashboardQuizTopicRoute,
  DashboardResultsAttemptIdRoute: DashboardResultsAttemptIdRoute,
  DashboardExperimentIdIndexRoute: DashboardExperimentIdIndexRoute,
  DashboardQuizIndexRoute: DashboardQuizIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
